apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-price-prediction
  labels:
    app: car-price-prediction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: car-price-prediction
  template:
    metadata:
      labels:
        app: car-price-prediction
    spec:
      containers:
      - name: car-price-prediction
        image: falex55/car-price-prediction
        ports:
        - containerPort: 5000
